export const PRODUCTS = {
    'women-kit-01': {
      title: 'Women Essential Kit',
      category: 'Women',
      price: 299.95,
      rating: 4.5,
      reviews: 128,
      stock: 25,
      description: 'Includes all the necessary things for daily health care, packed in a compact travel-friendly pouch.',
      images: ['../assets/women_kit.png'],
      colors: [{ name: 'Pink', hex: '#f4a6c0' }, { name: 'White', hex: '#f2f2f2' }],
      sizes: ['S', 'M', 'L']
    },
    'car-cover-01': {
      title: 'Car Cover',
      category: 'Automotive',
      price: 299.95,
      rating: 4,
      reviews: 64,
      stock: 12,
      description: 'Water-resistant, UV-protected cover from verified sellers. Elastic hem keeps it snug in strong wind.',
      images: ['../assets/car_cover.png'],
      colors: [{ name: 'Silver', hex: '#b8bcc2' }, { name: 'Black', hex: '#222222' }],
      sizes: ['S', 'M', 'L', 'XL']
    },
    'laptop-01': {
      title: 'Everyday Laptop',
      category: 'Electronics',
      price: 35990,
      rating: 4.5,
      reviews: 342,
      stock: 8,
      description: 'Pocket-friendly laptop for study and work, with a bright display and all-day battery life.',
      images: ['../assets/laptop.png', '../assets/laptops_group.png'],
      colors: [{ name: 'Silver', hex: '#c0c0c0' }, { name: 'Space Grey', hex: '#4b4f56' }]
    },
    'oppo-k13': {
      title: 'OPPO K13',
      category: 'Mobiles',
      price: 26990,
      rating: 4,
      reviews: 890,
      stock: 0,
      description: 'Flaunt it your way. Up to ₹2,500 instant off on select credit cards.',
      images: ['../assets/oppo_k13.png'],
      colors: [{ name: 'Blue', hex: '#3a6ea5' }, { name: 'Black', hex: '#1c1c1c' }]
    },
    'phone-1': {
    title: 'ONE PLUS NORD CE4',
    category: 'Mobiles',
    price: 27000,
    rating: 4.5,
    reviews: 142,
    stock: 15,
    description: 'Fast and smooth performance with an all-day battery and stunning display. Designed for everyday excellence.',
    images: ['../assets/phone1.png'],
    colors: [{ name: 'Black', hex: '#1c1c1c' }, { name: 'Cyan', hex: '#4bcffa' }],
    specifications: ['8GB / 128GB']
  },
  'phone-2': {
    title: 'NOTHING 7S',
    category: 'Mobiles',
    price: 37000,
    rating: 4.4,
    reviews: 98,
    stock: 10,
    description: 'Unique transparent design paired with a powerful processor and clean user interface.',
    images: ['../assets/phone2.png'],
    colors: [{ name: 'White', hex: '#f2f2f2' }, { name: 'Dark Grey', hex: '#333333' }],
    specifications: ['8GB / 256GB']
  },
  'phone-3': {
    title: 'GOOGLE PIXEL 7',
    category: 'Mobiles',
    price: 71000,
    rating: 4.7,
    reviews: 310,
    stock: 8,
    description: 'Advanced Google Tensor processing with professional-grade camera capabilities and smart features.',
    images: ['../assets/phone3.png'],
    colors: [{ name: 'Obsidian', hex: '#2b2b2b' }, { name: 'Snow', hex: '#f5f5f5' }],
    specifications: ['12GB / 256GB']
  },
  'phone-4': {
    title: 'VIVO Y21 7',
    category: 'Mobiles',
    price: 49000,
    rating: 4.2,
    reviews: 75,
    stock: 12,
    description: 'Sleek body with expansive storage and smooth multitasking capabilities for all your daily needs.',
    images: ['../assets/phone4.png'],
    colors: [{ name: 'Blue', hex: '#2c3e50' }, { name: 'Gold', hex: '#e67e22' }],
    specifications: ['12GB / 256GB']
  },
  'phone-5': {
    title: 'SAMSUNG S21',
    category: 'Mobiles',
    price: 121000,
    rating: 4.8,
    reviews: 512,
    stock: 5,
    description: 'Flagship tier smartphone featuring a high-resolution display and pro multi-lens camera layout.',
    images: ['../assets/phone6.png'],
    colors: [{ name: 'Phantom Black', hex: '#111111' }, { name: 'Silver', hex: '#bdc3c7' }],
    specifications: ['12GB / 512GB']
  },
  'phone-6': {
    title: 'I PHONE 14 PRO MAX C2',
    category: 'Mobiles',
    price: 141000,
    rating: 4.9,
    reviews: 840,
    stock: 6,
    description: 'The ultimate iPhone experience with Dynamic Island, an ultra-fast A-series chip, and cinematic video recording.',
    images: ['../assets/phone5.png'],
    colors: [{ name: 'Deep Purple', hex: '#4a3b5c' }, { name: 'Space Black', hex: '#212121' }],
    specifications: ['16GB / 512GB']
  },

  // --- Trending Offers ---
  'sanitizer': {
    title: 'Sanitizers',
    category: 'Trending Offers',
    price: 199,
    rating: 4.3,
    reviews: 45,
    stock: 50,
    description: 'Effective germ protection with skin-friendly moisturizers. Extra 5% off on bulk purchases.',
    images: ['../assets/sanitizer.png'],
    colors: [{ name: 'Clear', hex: '#ecf0f1' }],
    sizes: ['200ml', '500ml']
  },
  'masks': {
    title: 'Masks',
    category: 'Trending Offers',
    price: 299,
    rating: 4.5,
    reviews: 120,
    stock: 100,
    description: 'Breathable, multi-layered protective face masks for safe daily commuting and public use.',
    images: ['../assets/masks.png'],
    colors: [{ name: 'Blue', hex: '#2980b9' }, { name: 'Black', hex: '#2c3e50' }],
    sizes: ['Pack of 5']
  },
  'chair': {
    title: 'Chairs',
    category: 'Trending Offers',
    price: 4999,
    rating: 4.6,
    reviews: 88,
    stock: 14,
    description: 'Ergonomic office and study chairs built for maximum lumbar support and long working hours.',
    images: ['../assets/chair.png'],
    colors: [{ name: 'Black', hex: '#222222' }, { name: 'Grey', hex: '#7f8c8d' }],
    sizes: ['Standard']
  },
  'bedsheet': {
    title: 'Bedsheets',
    category: 'Trending Offers',
    price: 1299,
    rating: 4.4,
    reviews: 215,
    stock: 30,
    description: 'Soft cotton bedsheets with vibrant color patterns to enhance your bedroom décor aesthetics.',
    images: ['../assets/bedsheet.png'],
    colors: [{ name: 'Blue Floral', hex: '#3498db' }, { name: 'Maroon', hex: '#c0392b' }],
    sizes: ['Queen', 'King']
  },
  'handbags': {
    title: 'Handbags',
    category: 'Trending Offers',
    price: 2499,
    rating: 4.7,
    reviews: 160,
    stock: 20,
    description: 'Stylish, durable faux-leather handbags designed for daily utility and fashion styling.',
    images: ['../assets/handbags.png'],
    colors: [{ name: 'Tan', hex: '#d35400' }, { name: 'Black', hex: '#111111' }],
    sizes: ['Standard']
  },
  'painting': {
    title: 'Paintings',
    category: 'Trending Offers',
    price: 1799,
    rating: 4.5,
    reviews: 62,
    stock: 12,
    description: 'Hand-crafted decorative wall paintings to give your living space an artistic and lively touch.',
    images: ['../assets/painting.png'],
    colors: [{ name: 'Multi', hex: '#8e44ad' }],
    sizes: ['Medium', 'Large']
  }
  };